---

- name: Update global bashrc
  blockinfile:
    path: "{{ bashrc_global }}"
    block: |
      ### History settings ###
      shopt -s histappend
      export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
      export HISTTIMEFORMAT="[%Y-%m-%d %T] "
      export HISTCONTROL="ignoredups"
      export HISTSIZE=10000
      ########################

      export EDITOR='/usr/bin/vim'
    create: yes
  become: true

- name: Copy user bashrc
  template:
    src: files/.bashrc
    dest: ~/.bashrc

- name: Ensure user bashrc dir exist
  file:
    path: "{{ bashrc_user_dir }}"
    state: directory

- name: Copy aliases
  template:
    src: files/.bashrc.d/bash_aliases
    dest: "{{ bashrc_dir }}/bash_aliases"