---
- include_role:
    name: 0-common
  vars:
    packages: 
      - hyprland-devel
      - hyprlock
      - hypridle
      - hyprpaper
    config_dir_name: hypr
    config_files:
      - hyprland.conf
      - hyprlock.conf
      - hypridle.conf
      - hyprpaper.conf

- name: Install hyprshot
  include_tasks:
    file: hyprshot.yml