---
- include_role:
    name: 0-common
  vars:
    package: hyprland-devel
    config_dir_name: hypr
    config_files:
      - hyprland.conf

- name: Install hyprshot
  vars: 
    version: main
  get_url:
    url: "https://raw.githubusercontent.com/Gustash/hyprshot/{{ version }}/hyprshot"
    dest: /usr/local/bin/hyprshot
    mode: u=rwx,g=rx,o=rx
  become: true