---
- include_role:
    name: 0-common
  vars:
    packages: 
      - hyprland-devel
      - hyprlock
    config_dir_name: hypr
    config_files:
      - hyprland.conf
      - hyprlock.conf

- name: Install hyprshot
  vars: 
    version: main
  get_url:
    url: "https://raw.githubusercontent.com/Gustash/hyprshot/{{ version }}/hyprshot"
    dest: /usr/local/bin/hyprshot
    mode: u=rwx,g=rx,o=rx
  become: true