---
- name: Enable Fedora Copr for faster updates and additional packages
  community.general.copr:
    name: solopasha/hyprland
  become: true

- include_role:
    name: 0-common
  vars:
    packages: 
      - hyprland-devel
      - hyprlock
      - hypridle
      - hyprpaper
      - hyprsunset
    config_dir_name: hypr
    config_files:
      - hyprland.conf
      - hyprlock.conf
      - hypridle.conf
      - hyprpaper.conf

- name: Install hyprshot
  include_tasks:
    file: hyprshot.yml

- name: Install hyprsunset
  vars:
    script_path: /home/{{ user }}/.local/bin
  block:
  - name: Add hyprsunset wrapper
    template:
      src: files/hyprsunsetwrapper
      dest: "{{ script_path }}/hyprsunsetwrapper"
      mode: u=rwx,g=rx,o=

  - name: Add symlink
    file:
      src: "{{ script_path }}/hyprsunsetwrapper"
      dest: "/usr/bin/hyprsunsetwrapper"
      state: link
    become: true
    when: not ansible_check_mode