---
- name: Import key
  command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Add config
  copy:
    src: files/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
  become: true

- name: Check update
  dnf:
    update_cache: true
  become: true

- include_role:
    name: 0-common
  vars:
    package: code
    config_dir_name: Code/User
    config_files:
      - settings.json