---
- name: Add files
  block:
  - name: Add script
    template:
      src: "files/synclip"
      dest: "{{ script_fullpath }}/synclip"
      mode: u=rwx,g=rx,o=

- name: Add symlink
  file:
    src: "{{ script_fullpath }}/synclip"
    dest: "/usr/bin/synclip"
    state: link
  become: true
  when: not ansible_check_mode